---
- name: Install and start Apache HTTPD
  gather_facts: yes
  hosts: webservers
  become: yes 

  tasks:
    - name: httpd package is present 
      yum:
        name: httpd 
        state: present 

    - name: correct index.html is present 
      copy:
        src: /home/ansible/ansible/basic-playbook/index.html
        dest: /var/www/html/index.html 
    
    # Handlers
    - name: httpd is started
      service:
        name: httpd 
        state: started 
        enabled: true 
