---
- hosts: webservers
  become: yes

  tasks:
    
    - name: install apache2 and php packages for "Ubuntu"
      apt:
        name: 
          - apache2 
          - libapache2-mod-php
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"
       
    - name: install httpd and php packages for centos
      yum:
        name: 
          - httpd
          - php 
          - tree
        state: present
        update_cache: true
      when: ansible_distribution == "CentOS"
    
    # - name: copy index.html  
    #   template:
    #     src: /home/ansible/ferdows-ansible/ansible/basic-playbook/index.html
    #     dest: /var/www/html/index.html

    - name: start httpd service on centos dirstos
      service:
        name: httpd
        state:  started
        enabled:  true